on:
  pull_request:
    branches:
      - main
      - dev
      - ci

name: Pre-check

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.client.outputs.changed }}
      backend: ${{ steps.backend.outputs.changed }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Get changed client files
        id: client-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          files: client/**

      - name: Get changed backend files
        id: backend-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          files: backend/**

      - name: Check if client has changed files
        id: client
        if: steps.client-files.outputs.any_changed == 'true'
        run: echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Check if backend has changed files
        id: backend
        if: steps.backend-files.outputs.any_changed == 'true'
        run: echo "changed=true" >> "$GITHUB_OUTPUT"

  client:
    runs-on: ubuntu-latest
    if: ${{ needs.changed.outputs.client == 'true' }}
    defaults:
      run:
        working-directory: client
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: client/yarn.lock

      - name: Install project dependencies
        run: yarn --prefer-offline

      # - name: Test
      #   run: yarn test --passWithNoTests

      - name: "Build"
        run: yarn build

    needs: changed

  backend:
    runs-on: ubuntu-latest
    if: ${{ needs.changed.outputs.backend == 'true' }}
    defaults:
      run:
        working-directory: backend
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: backend/yarn.lock

      - name: Install project dependencies
        run: yarn --prefer-offline

      # - name: Test
      #   run: yarn test --passWithNoTests

      - name: "Build"
        run: yarn build

    needs: changed
